Reg
frontend-park-mail-ru/2022_1_KURAGA_TEAM pull request #10
Opened 2022-02-24 11:07 UTC by Amrion

2022-02-24 17:56 UTC, dnlipko requested changes

2022-02-24 17:56 UTC, dnlipko commented on registration.js
> +const telegram = document.createElement("img");
Похожий функционал по созданию блоков лучше вынести в отдельные метод 
Создание иконок телеграма ничем не отличаются от создания иконок инсты

2022-02-24 17:56 UTC, dnlipko commented on registration.js
> +const back = document.createElement("div");
Лучше создание блоков обернуть в функции. Сейчас это куча непонятного кода. Хочу чтобы по итогу  было описано несколько функций и в конце вызывался метод `createPage()`

А в createPage создавались топлайн контент и футтер и тд

2022-02-24 17:56 UTC, dnlipko commented on registration.js
> +const back = document.createElement("div");
Больше инкапсуляции логики)

2022-02-24 17:56 UTC, dnlipko commented on registration.css
> +#root {
лучше использовать классы а не айдишники там где это возможно

2022-02-24 17:56 UTC, dnlipko commented on index.html
> +    <meta name="theme-color" content="#01090B">
Чего здесь забыл метатег?

2022-02-24 17:56 UTC, dnlipko commented on registration.css
> +    width: 100%;
На корневой контейнер нужно навесить height: 100vh чтобы страница не скролилась и полностью помещалась на экран

2022-02-24 17:56 UTC, dnlipko commented on registration.css
> +h1 {
Плохо вешать стили на теги, это затронет все h1 на странице

2022-02-24 17:56 UTC, dnlipko commented on registration.css
> +form {
замени на класс

2022-02-24 17:56 UTC, dnlipko commented on registration.css
> +    font-family: GT Eesti Pro Display, arial, sans-serif;
Зачем тут повторение шрифта

2022-02-24 17:56 UTC, dnlipko commented on registration.css
> +    position: absolute;
Почему у меня position:absolute?
Кажется логичнее сделать absolute для подложки

2022-02-24 17:56 UTC, dnlipko commented on registration.js
> +        errorEmail.textContent = 'Введите действительный email';
Так точно говорят 'Действительный email'?
Требую какой-нибудь реф

2022-02-24 17:56 UTC, dnlipko commented on registration.css
> +    grid-template-columns: 350px 350px auto 300px;
Так как все события происходят в пределах одной строки, то тут проще было бы использовать флексы 
justify-content: space-between
И никакого лишнего third

2022-02-24 17:56 UTC, dnlipko commented on registration.css
> +    margin-left: 50px;
У title content refer точно можно убрать margin-left и сделать отступ на контейнере

2022-02-24 17:56 UTC, dnlipko commented on registration.js
> +const telegram = document.createElement("img");
Тут можно прям через массив [telData, instData].map(createIcon)

2022-02-24 17:56 UTC, dnlipko commented on registration.js
> +const telegram = document.createElement("img");
И с инпутами формы можно так же)

2022-02-24 17:56 UTC, dnlipko commented on registration.js
> +const telegram = document.createElement("img");
* любыми повторяющимися элементами на странице

2022-02-24 17:56 UTC, dnlipko commented on media.css
> +@media (min-height: 1200px) and (max-height: 1599px) {
Лучше на высоту не писать медиа запросы. Пусть появляется скролл, если что-то по высоте не влазит.

2022-02-24 17:56 UTC, dnlipko commented on media.css
> +    #menu{
Размер меню можно задать в px
В момент когда оно перестает вмещаться по ширине можно его уменьшить в px 
На слишком узких экранах нужно оставить какую-то минимальную ширину ниже которой меню уменьшаться не будет

2022-02-24 21:23 UTC, Amrion commented on registration.css
> +#root {
Мне лучше везде поменять id на классы? 
Не совсем понимаю, почему id не уместны, у меня же все элементы, которые повторятся несколько раз, используют классы, а вот которые один раз - id

2022-02-24 21:25 UTC, Amrion commented on media.css
> +@media (min-height: 1200px) and (max-height: 1599px) {
Почему стоит вернуть пиксели, почему плохи в этом случае проценты?

2022-02-24 21:25 UTC, Amrion commented on media.css
> +    #menu{
Почему стоит вернуть пиксели, почему плохи в этом случае проценты?

2022-02-24 21:25 UTC, Amrion commented on media.css
> +@media (min-height: 1200px) and (max-height: 1599px) {
У меня наоборот, если не задавать нужную высоту для определенных размеров высоты, то картинка будет не помещаться на весь экран

2022-02-25 02:21 UTC, dnlipko commented on registration.css
> +#root {
Использование id не очень хорошая практика так как в большом проекте сложно отследить какие id используются, а их дублирование может привести к ошибке. 
Повторение сильной роли не играет. #text #svg нужно убрать, на крупных блоках типа footer, menu можно оставить

2022-02-25 02:26 UTC, dnlipko commented on media.css
> +    #menu{
Это по большей части вкусовщина. В резиновом дизайне, который постоянной растягивается/сужается в зависимости от ширины экрана могут всплывать какие-то баги, которые не отследили из-за того что нужно постоянно ресайзить экран для теста. Когда размер блока задается в пикселях, известно что есть n(=2) кейсов как будет выглядеть твой блок, что гораздо проще тесть. 
Оставь на свой вкус)
+4 медиа запроса с изменением ширины меню это много

2022-03-03 20:04 UTC, merged