Dev
frontend-park-mail-ru/2022_1_KURAGA_TEAM pull request #12
Opened 2022-03-03 20:59 UTC by Amrion

2022-03-07 00:23 UTC, dnlipko requested changes

2022-03-07 00:23 UTC, dnlipko commented on src/components/footer/footerClass.js
> +        const configIcon = {
Можно вынести в константы чтобы объект не пересоздавался при каждом рендеринге

2022-03-07 00:23 UTC, dnlipko commented on src/components/button/button.pug
> +button.menu-button(type="submit") Зарегистрироваться
Можно сделать универсальную кнопку в которую пробрасываются текст и дополнительный класс для нее или обертки

2022-03-07 00:23 UTC, dnlipko commented on src/components/carousel/carousel.css
> +    color: #FFFFFF;
В `:root` можно сохранять цвета в переменные и использовать в css уже по идентификатору. Так удобнее отслеживать какие цвета используется в проекте, поддерживать их единообразие и если что сделать быстрый редизайн)

2022-03-07 00:23 UTC, dnlipko commented on src/components/carousel/carousel.css
> +}
Последняя пустая строка пропущены. В других файлах тоже

2022-03-07 00:23 UTC, dnlipko commented on src/components/carousel/carouselFam/carouselFamClass.js
> +        (function () {
Зачем здесь самовызывающаяся функция и use strict?

2022-03-07 00:23 UTC, dnlipko commented on src/components/carousel/carouselPop/carouselPop.pug
> +                each val in [1, 2, 3]
Давай подготовимся к тому что в шаблон у нас будут приходить сразу карусели с разным набором фильмов.  Сделай больше моканных фильмов и убери хардкод с [1, 2, 3]

2022-03-07 00:23 UTC, dnlipko commented on src/components/carousel/carouselPop/carouselPopClass.js
> +        (function () {
Зачем здесь самовызывающаяся функция и use strict?

2022-03-07 00:23 UTC, dnlipko commented on src/components/carousel/carouselPop/carouselPopClass.js
> +            "use strict";
Стоит здесь избавиться от лишнего кода

2022-03-07 00:23 UTC, dnlipko commented on src/components/carousel/carouselTop/carouselTop.css
> +body {
Это повторяется уже не в первом css файле. Чтобы избежать дублирования нужно вынести в common.css

2022-03-07 00:23 UTC, dnlipko commented on src/components/carousel/carouselTop/carouselTopClass.js
> +import carouselTopTemplate from "./carouselTop.js";
Чем отличаются carouselTop, carouselPop, carouselFam?

2022-03-07 00:23 UTC, dnlipko commented on src/components/header/headerClass.js
> +        const configProfile = {
В коснтанты

2022-03-07 00:23 UTC, dnlipko commented on src/components/header/headerClass.js
> +        const profile = Object.entries(configProfile).map(([key, {name, src}]) => ({key, name, src}));
Object.entries тут кажется лишним. Почему используется configProfile, а не объект user с полем name и src?

2022-03-07 00:23 UTC, dnlipko commented on src/components/inputs/inputs.css
> +    font-family: GT Eesti Pro Display Light, arial, sans-serif;
Сейчас одинаковый шрифт везде? Тогда его можно не указывать для каждого компонента, а навесить на body

2022-03-07 00:23 UTC, dnlipko commented on src/components/inputs/inputsLogin/inputsClass.js
> +        const configElement = {
константа

2022-03-07 00:23 UTC, dnlipko commented on src/components/inputs/inputsLogin/inputsClass.js
> +            email: {
Зачем создавать объект если данные для инпутов однотипные и можно создать массив с двумя объекта и полем key/name. Object.entries окажется не нужным

2022-03-07 00:23 UTC, dnlipko commented on src/components/inputs/inputsLogin/inputsClass.js
> +        function emailError() {
Стрелочные функции)

2022-03-07 00:23 UTC, dnlipko commented on src/components/inputs/inputsLogin/inputsClass.js
> +                login(form)
Login бы в модель пользователя затащить. Проверку статуса можно обернуть в промис чтобы в каждой вьюхе не писать if (Number(status) / 100 === 4)

2022-03-07 00:23 UTC, dnlipko commented on src/components/inputs/inputsReg/inputsClass.js
> +        const configElement = {
константы

2022-03-07 00:23 UTC, dnlipko commented on src/components/inputs/inputsReg/inputsClass.js
> +        const formElements = Object.entries(configElement)
Object.entries

2022-03-07 00:23 UTC, dnlipko commented on src/components/inputs/inputsReg/inputsClass.js
> +        function passOneError() {
() =>

2022-03-07 00:23 UTC, dnlipko commented on src/components/mainMovie/mainMovie.pug
> +mixin mainMovie(items)
items? mixin? Они точно тут нужны

2022-03-07 00:23 UTC, dnlipko commented on src/components/mainMovie/mainMovie.pug
> +        div.sidebar
Переделать на item который якобы приходит с сервера. Мокать в классе фильма

2022-03-07 00:23 UTC, dnlipko commented on src/modules/ajax.js
> +    const URL = `http://89.208.228.163:1323/api/v1 + ${path}`;
В константы http://89.208.228.163:1323/api/v1

2022-03-07 00:23 UTC, dnlipko commented on src/modules/ajax.js
> +            status = response.status;
Кажется тут не нужна хитрость с сохранением переменной status в контекст. Лучше сразу вернуть статус и responseBody: response.json()

2022-03-07 00:23 UTC, dnlipko commented on src/modules/network.js
> +        return await ajax({
Для удобства делают методы ajax.post ajax.get 
Пример https://github.com/axios/axios

2022-03-07 00:23 UTC, dnlipko commented on src/views/homeView/homeView.pug
> +                div.select-title Популярное
Переделать на то что с бэка приходит уже карусель. Данные замокать в homeViewClass.js

2022-03-07 00:23 UTC, dnlipko commented on src/views/homeView/homeViewClass.js
> +
Не хватает setHandler для обработки кликов на ссылки.

2022-03-07 00:23 UTC, dnlipko commented on src/views/loginView/loginViewClass.js
> +        Array.from(document.getElementsByTagName('a')).forEach((item) => {
Вынести в отдельный файл в папочке utils. Так как общий код для всех вьюх

2022-03-07 08:43 UTC, iiivan-lemon commented on src/components/carousel/carousel.css
> +}
исправил

2022-03-07 08:53 UTC, iiivan-lemon commented on src/views/homeView/homeViewClass.js
> +
добавил

2022-03-07 09:00 UTC, iiivan-lemon commented on src/components/carousel/carouselTop/carouselTopClass.js
> +import carouselTopTemplate from "./carouselTop.js";
пока глобально несильно чем, разные классы js-carousel для пролистывания для каждой карусели

2022-03-07 09:03 UTC, iiivan-lemon commented on src/components/carousel/carouselTop/carouselTop.css
> +body {
исправил, оставил в carousel.css

2022-03-07 09:31 UTC, iiivan-lemon commented on src/components/carousel/carousel.css
> +    color: #FFFFFF;
закинул в body

2022-03-07 09:39 UTC, iiivan-lemon commented on src/components/carousel/carouselPop/carouselPopClass.js
> +            "use strict";
исправил

2022-03-07 09:39 UTC, iiivan-lemon commented on src/components/carousel/carouselPop/carouselPopClass.js
> +        (function () {
исправил

2022-03-07 09:42 UTC, iiivan-lemon commented on src/components/header/headerClass.js
> +        const profile = Object.entries(configProfile).map(([key, {name, src}]) => ({key, name, src}));
исправил

2022-03-07 15:25 UTC, Amrion commented on src/components/inputs/inputsLogin/inputsClass.js
> +            email: {
У меня никак не получается без entries, так как мне нужно же передать именно ключ, ну то есть чтобы я мог итерироваться по ключу в том числе и по значениям

2022-03-07 15:44 UTC, Amrion commented on src/components/inputs/inputsReg/inputsClass.js
> +        const formElements = Object.entries(configElement)
Аналогично

2022-03-07 15:48 UTC, Amrion commented on src/components/inputs/inputsLogin/inputsClass.js
> +                login(form)
Немного не пойму
Ну если я перенесу проверку статуса в модуль туда, где я описывал запросы, то все равно же в каждой вьюхе статус 4xx будет опоздачать разные вещи, и я должен буду по-разному реагировать
То есть все равно в каждой вьюхе я должен буду делать проверку на статус

2022-03-07 16:02 UTC, dnlipko commented on src/components/carousel/carouselFam/carouselFamClass.js
> +        function Carousel(setting) {
function Carousel можно вынести в отдельный файл как минимум

2022-03-07 16:11 UTC, dnlipko commented on src/components/carousel/carousel.css
> +    color: #FFFFFF;
https://teamtreehouse.com/community/applying-backgroundcolor-to-root-vs-body

2022-03-07 16:12 UTC, dnlipko commented on src/components/carousel/carousel.css
> +    color: #FFFFFF;
Лучше в :root это бест практис
CSS переменные
https://developer.mozilla.org/ru/docs/Web/CSS/Using_CSS_custom_properties
https://developer.mozilla.org/ru/docs/Web/CSS/:root

2022-03-07 16:49 UTC, dnlipko commented on src/components/inputs/inputsLogin/inputsClass.js
> +                login(form)
Вьюха не должна хранить информацию о том какие есть статусы ответа и как они обрабатываются. Во вьху лучше передавать набор флагов isAuth error data. Тогда во вьюхе не нужно вспоминать как обрабатывать статус ответа, а достаточно воспользоваться флагами

2022-03-07 17:04 UTC, dnlipko commented on src/components/inputs/inputsLogin/inputsClass.js
> +            email: {
В чем проблема сразу создать список объектов с полями {key, data, placeholder, type, error}?

2022-03-07 19:49 UTC, dnlipko commented on src/components/footer/footerClass.js
>          const footerIcons = Object.entries(configIcon).map(([key, {href, src}]) => ({key, href, src}));
Так и не понял почему нельзя сделать так?

const configIcons = {
    {
        key: telegram
        href: "/",
        src: "../../static/telegram.png",
    },
   {
        key: instagram
        href: "https://www.instagram.com/danyatarnovskiy/",
        src: "../../static/insta.png",
    },
    {
        key: vk
        href: "https://vk.com/dtarnovsky",
        src: "../../static/vk.png",
    }
};

return footerTemplate(configIcons);

2022-03-07 19:52 UTC, dnlipko commented on src/utils/handlerLink.js
> +export function setHandler() {
Лучше назвать метод по лучше. А то с ходу не понятно что за setHandler. Название файла уже лучше)

2022-03-07 19:53 UTC, dnlipko commented on src/views/regView/regViewClass.js
> +            button: button.render("Зарегистрироваться", ""),
Класс можно не передавать. Укажите дефолтное значение для него в рендере кнопки

2022-03-07 20:00 UTC, dnlipko commented on package.json
> +    "express": "^4.17.3",
express, express-history-api-fallback, morgan, pug нужны для разработки(дев зависимости)

2022-03-07 20:02 UTC, dnlipko commented on package.json
> +    "lint": "node_modules/.bin/eslint src/"
Странный способ вызвать eslint
https://stackoverflow.com/questions/36307581/how-to-configure-package-json-to-run-eslint-script

2022-03-07 20:03 UTC, dnlipko commented on package.json
> +  "main": ".eslintrc.js",
eslintrc.js?
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#main

2022-03-07 20:04 UTC, dnlipko commented on src/components/button/button.css
> +    background: linear-gradient(90deg, #A6418D -12.3%, #24469D 93.57%);
Цвета в константы в :root

2022-03-07 20:05 UTC, dnlipko commented on src/components/carousel/carousel.css
> +    color: #ffffffc2;
Цвета в константы

2022-03-07 20:05 UTC, dnlipko commented on src/components/carousel/carousel.css
> +    color: #707070;
Цвета в константы

2022-03-07 20:06 UTC, dnlipko commented on src/components/carousel/carouselFam/carouselFamClass.js
> +        const Movies = [
в константы

2022-03-07 20:07 UTC, dnlipko commented on src/components/carousel/carouselPop/carouselPopClass.js
> +        const Movies = [
в константы

2022-03-07 20:08 UTC, dnlipko commented on src/components/carousel/carouselPop/carouselPopClass.js
> +        function Carousel(setting) {
В отдельный компонент

2022-03-07 20:09 UTC, dnlipko commented on src/components/carousel/carouselTop/carouselTop.css
> +    background-color: #ffffff1c;
в переменную

2022-03-07 20:09 UTC, dnlipko commented on src/components/carousel/carouselTop/carouselTop.css
> +    background-color: rgb(196 196 196 / 8%);
в переменную

2022-03-07 20:09 UTC, dnlipko commented on src/components/footer/footer.css
> +    color: #C3C3C2;
переменная

2022-03-07 20:09 UTC, dnlipko commented on src/components/footer/footer.css
> +    color: #C3C3C2;
переменная

2022-03-07 20:10 UTC, dnlipko commented on src/components/header/header.pug
> +
Что с отступом стало?

2022-03-07 20:10 UTC, dnlipko commented on src/components/header/headerClass.js
> +        const configUser= {
В константу

2022-03-07 20:11 UTC, dnlipko commented on src/components/inputs/inputs.css
> +    background: rgba(0, 0, 0, 0);
css переменная

2022-03-07 20:14 UTC, dnlipko commented on src/css/home.css
> +p + p {
Стили на тегах это плохо, особенно глобально

2022-03-07 20:14 UTC, dnlipko commented on src/css/home.css
> +h2 {
Стили на тегах это плохо, особенно глобально

2022-03-07 20:15 UTC, dnlipko commented on src/css/registration.css
> +    background: #01090B;
css переменный

2022-03-07 20:16 UTC, dnlipko commented on src/modules/ajax.js
> +            return err;
Лучше здесь возвращать тот же набор полей что и выше но добавить поле error и isError: true

2022-03-07 20:17 UTC, dnlipko commented on src/routing/router.js
> +       let currentView = this.routes[window.location.pathname];
const

2022-03-07 20:19 UTC, dnlipko commented on src/routing/router.js
> +           currentView = this.routes[window.location.pathname];
Почему бы здесь не создать локальную переменную. Зачем присваивать в currentView

2022-03-07 21:53 UTC, iiivan-lemon commented on src/components/mainMovie/mainMovie.pug
> +mixin mainMovie(items)
нужны, хотели менять картинки и описание главного фильма

2022-03-07 21:55 UTC, iiivan-lemon commented on src/css/home.css
> +p + p {
убрал

2022-03-07 21:56 UTC, iiivan-lemon commented on src/css/home.css
> +h2 {
убрал

2022-03-07 21:56 UTC, iiivan-lemon commented on src/components/header/header.pug
> +
исправил

2022-03-07 22:09 UTC, iiivan-lemon commented on src/components/carousel/carouselPop/carouselPopClass.js
> +        function Carousel(setting) {
отделил

2022-03-07 22:46 UTC, iiivan-lemon commented on src/components/button/button.css
> +    background: linear-gradient(90deg, #A6418D -12.3%, #24469D 93.57%);
добавил

2022-03-07 22:46 UTC, iiivan-lemon commented on src/components/carousel/carousel.css
> +    color: #ffffffc2;
добавил

2022-03-07 22:46 UTC, iiivan-lemon commented on src/components/carousel/carousel.css
> +    color: #707070;
добавил

2022-03-07 22:47 UTC, iiivan-lemon commented on src/components/carousel/carouselTop/carouselTop.css
> +    background-color: #ffffff1c;
добавил

2022-03-07 22:47 UTC, iiivan-lemon commented on src/components/carousel/carouselFam/carouselFamClass.js
> +        const Movies = [
добавил

2022-03-07 22:58 UTC, iiivan-lemon commented on src/components/button/button.css
> +    background: linear-gradient(90deg, #A6418D -12.3%, #24469D 93.57%);
убрал

2022-03-07 23:01 UTC, iiivan-lemon commented on src/components/carousel/carouselTop/carouselTop.css
> +    background-color: rgb(196 196 196 / 8%);
добавил

2022-03-08 10:42 UTC, dnlipko commented on src/modules/ajax.js
> +            console.log(response.status);
Логирование убираем

2022-03-08 10:43 UTC, dnlipko commented on src/components/inputs/inputsLogin/inputsClass.js
> +                const formJson = JSON.stringify({
Почему форма по итогу здесь создается а не в login?

2022-03-08 10:44 UTC, dnlipko commented on src/modules/network.js
>      try {
Лучше создавать formdata тут чтобы не дублировать ее создание везде где вызывается login

2022-03-08 10:46 UTC, dnlipko commented on src/views/homeView/homeViewClass.js
> +    Handler() {
Почему метод класса называется с большой буквы? 

Функцию setHandler из utils нужно переименовать в более понятное название

2022-03-08 10:47 UTC, dnlipko commented on src/views/homeView/homeViewClass.js
>          console.log(quit);
Лог убрать

2022-03-08 10:48 UTC, dnlipko commented on src/components/header/headerClass.js
> +                    if (Number(status) / 100 === 4) {
Number(status) / 100 === 4 эту логику убрали в запросы и закрыли под флагами

2022-03-08 10:59 UTC, dnlipko commented on src/css/media.css
> +    #menu{
Почему бы создать эти стили в файлах соответствующих компонентов. А 1000px внести в переменную

2022-03-08 11:00 UTC, dnlipko commented on src/css/registration.css
> +body {
Этот стиль нужно перенести в common.css у на всех страницах шрифты на body будут одинаковыми

2022-03-08 11:01 UTC, dnlipko commented on src/css/registration.css
> +@font-face {
Это тоже должно быть в common.css который будет подключаться на все страницы

2022-03-08 13:21 UTC, dnlipko commented on src/components/carousel/carouselClass.js
> +    render() {
Список фильмов тоже передавай в конструкторе

2022-03-08 16:44 UTC, dnlipko commented on src/views/loginView/loginViewClass.js
> +            button: button.render("Войти"),
Название кнопки все таки лучше передавать в конструктор

2022-03-08 16:44 UTC, dnlipko commented on src/views/homeView/homeViewClass.js
> +                if (isAuth) {
Это условие здесь уже не нужно. Если до сюда дошел код то isAuth точно true

2022-03-08 16:47 UTC, dnlipko commented on src/components/carousel/carouselClass.js
> +import carouselPopTemplate from "./carousel.js";
carouselTemplate

2022-03-08 21:47 UTC, dnlipko commented on index.html
> +</html>
Новая строка в конце файла)

2022-03-08 21:48 UTC, dnlipko commented on src/components/button/button.css
> +}
Проверьте везде где нет пустых строк в конце, в изменениях в гите это хорошо видно

2022-03-08 21:50 UTC, dnlipko commented on src/components/carousel/carousel.css
> +body {
Здесь не должно быть стиля для body

2022-03-08 21:50 UTC, dnlipko commented on src/components/carousel/carousel.css
> +
Ну что отступы линтер для css нужно прогнать

2022-03-08 21:52 UTC, dnlipko commented on src/components/header/headerClass.js
> +        console.log(this.#name);
логи не забываем убирать

2022-03-08 21:54 UTC, dnlipko commented on src/modules/ajax.js
> +        statusInfo = 'Information';
Можно сразу return 'Information'

2022-03-08 21:54 UTC, dnlipko commented on src/modules/ajax.js
> +        statusInfo = 'Undefined';
Немного сбивает с толку строка 'Undefined'
Может лучше сделать return;

2022-03-08 21:55 UTC, dnlipko commented on src/modules/ajax.js
> +                        .then((res) => res),
.then((res) => res) не нужен

2022-03-08 21:55 UTC, dnlipko commented on src/modules/ajax.js
> +                    .then((response) => response),
.then((response) => response), бессмысленно

2022-03-09 05:22 UTC, dnlipko commented on src/components/header/header.css
> +    font-family: "GT Eesti Pro Display arial"m, arial, sans-serif;
Это что ща шрифт?

2022-03-09 07:23 UTC, iiivan-lemon commented on src/views/homeView/homeView.pug
> +                div.select-title Популярное
из бэка буду тпризодить фильмы, а сами карусели будут на фронте

2022-03-09 15:28 UTC, dnlipko approved these changes

2022-03-09 15:31 UTC, merged