Film
frontend-park-mail-ru/2022_1_KURAGA_TEAM pull request #17
Opened 2022-03-18 14:57 UTC by Amrion

2022-03-18 15:40 UTC, dnlipko requested changes

2022-03-18 15:40 UTC, dnlipko commented on src/components/headMovie/headMovieClass.js
> +        this.#year = params[0];
А почему они сюда массивом передаются а не объектом?

2022-03-18 15:40 UTC, dnlipko commented on src/index.html
>      <link href="css/home.css" type="text/css" rel="stylesheet">
Почему здесь подключаются стили, они должны вебпаком собираться и подключаться?

2022-03-18 15:40 UTC, dnlipko commented on src/modules/ajax.js
> +const API_URL = 'http://localhost:1323/api/v1';
не забываем менять обратно

2022-03-18 15:40 UTC, dnlipko commented on src/modules/ajax.js
> +        return 'Unknown';
'Unknown' странная конструкция. Может просто return;

2022-03-18 15:40 UTC, dnlipko commented on src/routing/router.js
> +            pathname = '/movie/id';
хардкод зарегистрированного в роутере урла '/movie/id' 

В методе go не должно происходить рендера вьюх, это происходит в обработчике события popstate
Здесь только добавляется состояние в историю window.history.pushState(null, null, path);

2022-03-18 15:40 UTC, dnlipko commented on src/routing/router.js
> +            let result = window.location.pathname.match(/movie\/(\d+)/);
Здесь не должно быть хардкода /movie/ потому что в дальшейшем появятся /actor /user /smthelse

Дава сделаем так. Будем регитсрировать в роутере
'/artist',
'/movie',
и в рендер методе вьюхи парсить id из урла. Это тоже небольшой хардкод, но он будет уже не в роутере

2022-03-18 15:40 UTC, dnlipko commented on src/views/movieView/movieViewClass.js
> +        let id = document.location.pathname.slice(7);
Что за slice 7)

2022-03-18 15:40 UTC, dnlipko commented on src/views/movieView/movieViewClass.js
> +                        if (movieRes.status === 500) {
Вынеси статусы в константы

2022-03-18 15:40 UTC, dnlipko commented on src/views/movieView/movieViewClass.js
> +                            router.go('/error');
Возможные роуты тоже в константы

2022-03-18 15:40 UTC, dnlipko commented on src/views/errorView/errorViewClass.js
> +        profile()
На странице ошибки нужна проверка на залогин?

2022-03-18 18:07 UTC, Amrion commented on src/routing/router.js
> +            let result = window.location.pathname.match(/movie\/(\d+)/);
Описал в ТГ

2022-03-18 18:07 UTC, Amrion commented on src/routing/router.js
> +            pathname = '/movie/id';
Описал в ТГ

2022-03-18 18:11 UTC, Amrion commented on src/views/errorView/errorViewClass.js
> +        profile()
Ну у нас же все равно ты ни на какие урлы пойти не можешь, пока не залогинишься, это раз)
А во-вторых, там на странице ошибки у меня есть навбар, ну чтобы с нее быстренько уйти на другие страницы. А в навбаре данные есть пользователя

2022-03-20 07:50 UTC, dnlipko commented on build/index.html
> +<!doctype html><html lang="ru"><head><meta charset="UTF-8"><meta name="description" content="Streaming service, Technopark project"><meta name="keywords" content="Movie, Serials, Netflix"><meta name=
Build нужно удалить

2022-03-20 07:54 UTC, dnlipko commented on src/views/movieView/movieViewClass.js
> +                        const headMovie = new HeadMovieClass(movieRes.year, movieRes.genre, movieRes.country,
Можно здесь передать сразу movieRes

А в constructor  использовать [деструктуризацию объекта](https://learn.javascript.ru/destructuring-assignment#destrukturizatsiya-obekta) constructor({year, genre, country,

2022-03-20 07:57 UTC, dnlipko commented on src/views/movieView/movieViewClass.js
> +                        const headMovie = new HeadMovieClass(movieRes.year, movieRes.genre, movieRes.country,
Почему этот способ лучше. Во первых он короче, во вторых если с деструктуризацией объекта можно добавить несколько опциональных параметров(уже заданных по дефолту), в случае с передачей параметров по отдельности можно создать только один опциональный параметр

2022-03-20 08:58 UTC, merged